# NORMALIZATION PROBLEM

In [2]:
import numpy as np

#Creating an array with 5 rows and columns containing random elements
x = np.random.rand(5,5)

#Setting formulas to normalize th elements of array x
mean = x.mean()
std = x.std()
z = (x - mean)/std

#Saving the normalized array
np.save('X_normalized.npy', z)

#Printing non-normalized array
print("Non-normalized:")
print(x)

#Printing normalized array
print("Normalized:")
print(z)

Non-normalized:
[[0.63128835 0.07341865 0.08969162 0.07512302 0.47208587]
 [0.55110589 0.39647087 0.32061696 0.06439208 0.32472163]
 [0.90722083 0.96407021 0.72699384 0.07711589 0.03615251]
 [0.06826285 0.09966387 0.53725535 0.77908941 0.49248637]
 [0.23908828 0.4236128  0.8196777  0.39753887 0.76414098]]
Normalized:
[[ 0.74596941 -1.16266905 -1.10699437 -1.15683787  0.20129028]
 [ 0.47164133 -0.05741116 -0.31692996 -1.19355161 -0.30288669]
 [ 1.69001661  1.8845153   1.07340639 -1.15001966 -1.2901676 ]
 [-1.18030857 -1.0728763   0.42425448  1.25164084  0.27108647]
 [-0.59586387  0.03544948  1.39050548 -0.05375721  1.20049783]]


# DIVISIBLE BY 3 PROBLEM

In [5]:
import numpy as np

#Creating an array containing the first 100 positive integers
x = np.arange(1,101)

#Squaring the elements of the array
y = x**2

#Making the array into 10 rows and columns
z = y.reshape(10,10)

#Getting the elements divisible by 3 and putting it in its own array
divisible3 = y[y%3==0]

#Saving the array with elements divisible by 3
np.save('div_by_3.npy', divisible3)

#Printing the 10x10 array containing the square of the first 100 positive integers
print("The square of the first 100 positive integers are:")
print(z)

#Printing the elements of the 10x10 array that are divisible by 3
print("The integers that are divisibe by 3 are:")
print(divisible3)    

The square of the first 100 positive integers are:
[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
The integers that are divisibe by 3 are:
[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
